a.tipo
, a.telefono
, a.fecha_movimiento_mes
, a.canal_movimiento_mes
, a.sub_canal_movimiento_mes
, a.nuevo_sub_canal_movimiento_mes
, a.distribuidor_movimiento_mes
, a.oficina_movimiento_mes
, a.portabilidad_movimiento_mes
, a.operadora_origen_movimiento_mes
, a.operadora_destino_movimiento_mes
, a.motivo_movimiento_mes
, a.cod_plan_anterior_movimiento_mes
, a.des_plan_anterior_movimiento_mes
, a.tb_descuento_movimiento_mes
, a.tb_override_movimiento_mes
, a.delta_movimiento_mes
, a.sub_movimiento
, a.imei
, a.equipo
, a.icc
, a.domain_login_ow
, a.nombre_usuario_ow
, a.domain_login_sub
, a.nombre_usuario_sub
, a.forma_pago
, a.codigo_usuario
, a.calf_riesgo
, a.cap_endeu
, a.valor_cred
, a.ciudad_usuario
, a.provincia_usuario
, a.ciudad
, a.provincia_activacion
, a.distribuidor_crm
, a.canal_transacc
, a.cod_da
, a.campania_movimiento_mes
, a.region