
---PARAMETROS PARA LA ENTIDAD OTC_T_360_MOVIMIENTOS_PARQUE
DELETE FROM params WHERE entidad='OTC_T_360_MOVIMIENTOS_PARQUE';
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','RUTA','/RGenerator/reportes/Cliente360','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','SHELL','/RGenerator/reportes/Cliente360/Bin/OTC_T_360_MOVIMIENTOS_PARQUE.sh','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','RUTA_LOG','/RGenerator/reportes/Cliente360/Log','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','RUTA_PYTHON','/RGenerator/reportes/Cliente360/Python','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','VAL_ESQUEMA_TMP','db_temporales','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','VAL_ESQUEMA_REP','db_reportes','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','vTAltBajHist','db_reportes.otc_t_alta_baja_hist','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','vTAltBI','db_cs_altas.otc_t_altas_bi','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','vTBajBI','db_cs_altas.otc_t_bajas_bi','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','vTTransfHist','db_reportes.otc_t_transfer_hist','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','vTTrInBI','db_cs_altas.otc_t_transfer_in_bi','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','vTTrOutBI','db_cs_altas.otc_t_transfer_out_bi','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','vTCPHist','db_reportes.otc_t_cambio_plan_hist','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','vTCPBI','db_cs_altas.otc_t_cambio_plan_bi','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','vTNRCSA','db_cs_altas.no_reciclable','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','vTCatPosUsr','db_cs_altas.otc_t_ctl_pos_usr_nc','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','vTCatPreUsr','db_cs_altas.otc_t_ctl_pre_usr_nc','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','vTPivotParq','db_temporales.otc_t_360_parque_1_tmp','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','VAL_ETP01_MASTER','yarn','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','VAL_ETP01_DRIVER_MEMORY','8G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','VAL_ETP01_EXECUTOR_MEMORY','16G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','VAL_ETP01_NUM_EXECUTORS','5','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','VAL_ETP01_NUM_EXECUTORS_CORES','3','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','ETAPA','1','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_MOVIMIENTOS_PARQUE','VAL_COLA_EJECUCION','reportes','0','1');


--PARAMETROS PARA LA ENTIDAD OTC_T_360_GENERAL
DELETE FROM params WHERE ENTIDAD='OTC_T_360_GENERAL';
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_GENERAL','RUTA','/RGenerator/reportes/Cliente360','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_GENERAL','SHELL','/RGenerator/reportes/Cliente360/Bin/OTC_T_360_GENERAL.sh','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_GENERAL','RUTA_LOG','/RGenerator/reportes/Cliente360/Log','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_GENERAL','RUTA_PYTHON','/RGenerator/reportes/Cliente360/Python','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_GENERAL','FILE_PYTHON','otc_t_360_general.py','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_GENERAL','PASO','1','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_GENERAL','HIVEDB','db_reportes','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_GENERAL','HIVETABLE','otc_t_360_general','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_GENERAL','ESQUEMA_TEMP','db_temporales','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_GENERAL','ESQUEMA_TEMP_READ','db_temporales','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_GENERAL','PATH_QUERY','/RGenerator/reportes/Cliente360/Python/Querys','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_GENERAL','PATH_CONF','/RGenerator/reportes/Cliente360/Python/Configuraciones','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_GENERAL','QUEUE','reportes','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_GENERAL','PESOS_PARAMETROS',' 0.45;0.05;0.40;0.04;0.02;0.02;0.02','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_GENERAL','PESOS_NSE','0.80;0.60;0.40;0.20;0.00','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_GENERAL','TOPE_RECARGAS','45','0','1');

INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_GENERAL','TOPE_TARIFA_BASICA','45','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_GENERAL','ESQUEMA_TABLA','db_thebox','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_GENERAL','ESQUEMA_TABLA_1','db_files_novum','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_GENERAL','ESQUEMA_TABLA_2','db_thebox','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_GENERAL','ESQUEMA_TABLA_3','db_payment_manager','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_GENERAL','TIPO_CARGA','append','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_GENERAL','VAL_MASTER','yarn','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_GENERAL','VAL_DRIVER_MEMORY','16G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_GENERAL','VAL_EXECUTOR_MEMORY','16G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_GENERAL','VAL_NUM_EXECUTORS','7','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_GENERAL','VAL_NUM_EXECUTORS_CORES','4','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_GENERAL','vDRIVER_MEMORY','8G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_GENERAL','vEXECUTOR_MEMORY','16G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_GENERAL','vNUM_EXECUTORS','4','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_GENERAL','vNUM_EXECUTORS_CORES','4','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_GENERAL','VAL_ESQUEMA_HIVE','db_reportes','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_GENERAL','VAL_TABLA_HIVE','otc_t_desc_no_pymes','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_GENERAL','VAL_NOM_FILE_IN','BASE_CARGA_DESCUENTO_NO_PYMES.xlsx','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_360_GENERAL','VAL_SFTP_RUTA_IN','/COMISIONES/Indirectos/Multipais/PROYECTO_COMISIONES/MOVIMIENTOS','0','1');


--PARAMETROS PARA LA ENTIDAD OTC_T_AJUSTES_MOVIMIENTOS
DELETE FROM params WHERE entidad='OTC_T_AJUSTES_MOVIMIENTOS';
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_AJUSTES_MOVIMIENTOS','ETAPA','1',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_AJUSTES_MOVIMIENTOS','VAL_RUTA','/Movimientos',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_AJUSTES_MOVIMIENTOS','VAL_FTP_RUTA','"/MOVIMIENTOS"',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_AJUSTES_MOVIMIENTOS','VAL_FTP_PUERTO','9694',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_AJUSTES_MOVIMIENTOS','VAL_FTP_HOSTNAME','fileuio03',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_AJUSTES_MOVIMIENTOS','VAL_FTP_PASS','bii2022-NA10',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_AJUSTES_MOVIMIENTOS','VAL_FTP_NOM_ARCHIVO','AJUSTES_MOVIMIENTOS.xlsx',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_AJUSTES_MOVIMIENTOS','VAL_DIR_HDFS_CAT','db_reportes.otc_t_ajustes_movimientos',1,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_AJUSTES_MOVIMIENTOS','VAL_FTP_USER','NABIFI01',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_AJUSTES_MOVIMIENTOS','vMASTER','yarn','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_AJUSTES_MOVIMIENTOS','vDRIVER_MEMORY','8G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_AJUSTES_MOVIMIENTOS','vEXECUTOR_MEMORY','16G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_AJUSTES_MOVIMIENTOS','vNUM_EXECUTORS','4','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_AJUSTES_MOVIMIENTOS','vNUM_EXECUTORS_CORES','4','0','1');
SELECT * FROM params WHERE ENTIDAD='OTC_T_AJUSTES_MOVIMIENTOS';

--PARAMETROS PARA LA ENTIDAD OTC_T_COMBO_INICIAL
DELETE FROM params WHERE entidad='OTC_T_COMBO_INICIAL';
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_COMBO_INICIAL','ETAPA','1',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_COMBO_INICIAL','VAL_RUTA','/Movimientos',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_COMBO_INICIAL','VAL_FTP_RUTA','"/MOVIMIENTOS"',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_COMBO_INICIAL','VAL_FTP_PUERTO','9694',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_COMBO_INICIAL','VAL_FTP_HOSTNAME','fileuio03',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_COMBO_INICIAL','VAL_FTP_PASS','bii2022-NA10',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_COMBO_INICIAL','VAL_FTP_NOM_ARCHIVO','COMBO_INICIAL.xlsx',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_COMBO_INICIAL','VAL_DIR_HDFS_CAT','db_reportes.otc_t_combo_inicial',1,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_COMBO_INICIAL','VAL_FTP_USER','NABIFI01',0,1);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_COMBO_INICIAL','vMASTER','yarn','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_COMBO_INICIAL','vDRIVER_MEMORY','8G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_COMBO_INICIAL','vEXECUTOR_MEMORY','16G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_COMBO_INICIAL','vNUM_EXECUTORS','4','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_COMBO_INICIAL','vNUM_EXECUTORS_CORES','4','0','1');
SELECT * FROM params WHERE ENTIDAD='OTC_T_COMBO_INICIAL';

-------PARAMS PARA EXTRACTOR DE MOVIMIENTOS
DELETE FROM params WHERE entidad='EXT_MVMNTS0070';
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0070','ETAPA','1',0,0);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0070','vRUTA','/Movimientos',0,0);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0070','vFTP_RUTA_OUT','/PROYECTO_COMISIONES_PRODUCCION/EXT_MOVIMIENTOS',0,0);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0070','vFTP_USER_OUT','NABIFI01',0,0);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0070','vFTP_PUERTO_OUT','9694',0,0);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0070','vFTP_HOSTNAME_OUT','fileuio03',0,0);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0070','vFTP_PASS_OUT','bii2022-NA10',0,0);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0070','vFTP_NOM_ARCHIVO','Extractor_Movimientos_',0,0);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0070','vRUTA_IN','/Movimientos/Input',0,0);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0070','vARCH_XTRCTR','/Movimientos/Input/Extractor_Movimientos.txt',0,0);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0070','vTMain','db_reportes.otc_t_ext_movimientos',0,0);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0070','vTAjust','db_reportes.otc_t_ajustes_movimientos',0,0);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0070','vNOM_PROCESO','EXTRACTOR_DE_MOVIMIENTOS',0,0);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0070','vSFTP_PUERTO_OUT','22','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0070','vSFTP_USER_OUT','telefonicaecuadorprod','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0070','vSFTP_HOSTNAME_OUT','ftp.cloud.varicent.com','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0070','vSFTP_PASS_OUT','RqiZ2lkJmeiQTi2hvRwd','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0070','vSFTP_RUTA_OUT','/Data','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0070','vNOM_ARCHIVO_OUT','Extractor_Movimientos','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0070','vMASTER','yarn','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0070','vDRIVER_MEMORY','16G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0070','vEXECUTOR_MEMORY','16G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0070','vNUM_EXECUTORS','8','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0070','vNUM_EXECUTORS_CORES','8','0','1');
SELECT * FROM params WHERE ENTIDAD='EXT_MVMNTS0070';

-- PARAMS PARA BASE_CARGA_DESCUENTO_NO_PYMES
DELETE FROM params WHERE entidad='OTC_T_DESC_NO_PYMES';
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_DESC_NO_PYMES','ETAPA','1',0,0);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_DESC_NO_PYMES','VAL_RUTA','/RAW/ARCHIVOS/OTC_T_DESC_NO_PYMES',0,0);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_DESC_NO_PYMES','SHELL','/RAW/ARCHIVOS/OTC_T_DESC_NO_PYMES/Bin/OTC_T_DESC_NO_PYMES.sh',0,0);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_DESC_NO_PYMES','VAL_FTP_RUTA','"/MOVIMIENTOS"',0,0);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_DESC_NO_PYMES','VAL_FTP_PUERTO','9694',0,0);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_DESC_NO_PYMES','VAL_FTP_HOSTNAME','fileuio03',0,0);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_DESC_NO_PYMES','VAL_FTP_PASS','bii2022-NA10',0,0);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_DESC_NO_PYMES','VAL_FTP_NOM_ARCHIVO','BASE_CARGA_DESCUENTO_NO_PYMES.xlsx',0,0);
insert into params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_DESC_NO_PYMES','VAL_DIR_HDFS_CAT','db_reportes.otc_t_desc_no_pymes',1,0);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_DESC_NO_PYMES','VAL_FTP_USER','NABIFI01',0,0);
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_DESC_NO_PYMES','vMASTER','yarn','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_DESC_NO_PYMES','vDRIVER_MEMORY','8G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_DESC_NO_PYMES','vEXECUTOR_MEMORY','16G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_DESC_NO_PYMES','vNUM_EXECUTORS','4','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_DESC_NO_PYMES','vNUM_EXECUTORS_CORES','4','0','1');
SELECT * FROM params WHERE ENTIDAD='OTC_T_DESC_NO_PYMES';

--PARAMETROS PARA LA ENTIDAD OTC_T_SOLICIT_PORT_IN
DELETE FROM params WHERE entidad='OTC_T_SOLICIT_PORT_IN';
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_SOLICIT_PORT_IN','HIVEDB','db_rdb','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_SOLICIT_PORT_IN','HIVETABLE','otc_t_solicit_port_in','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_SOLICIT_PORT_IN','RUTA','/RAW/RDB/OTC_T_SOLICIT_PORT_IN','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_SOLICIT_PORT_IN','SHELL','/RAW/RDB/OTC_T_SOLICIT_PORT_IN/Bin/OTC_T_SOLICIT_PORT_IN.sh','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_SOLICIT_PORT_IN','TDDB','tomstby.otecel.com.ec','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_SOLICIT_PORT_IN','TDHOST','proxfulldg1.otecel.com.ec','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_SOLICIT_PORT_IN','TDPASS','TelfEcu2017','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_SOLICIT_PORT_IN','TDUSER','rdb_reportes','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_SOLICIT_PORT_IN','TDPORT','7594','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_SOLICIT_PORT_IN','RUTA_LOG','/RAW/RDB/OTC_T_SOLICIT_PORT_IN/Log','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_SOLICIT_PORT_IN','TDSERVICE','sasdb.otecel.com.ec','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_SOLICIT_PORT_IN','ETAPA','1','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_SOLICIT_PORT_IN','RUTA_PYTHON','/RAW/RDB/OTC_T_SOLICIT_PORT_IN/Python','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_SOLICIT_PORT_IN','VAL_MASTER','local','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_SOLICIT_PORT_IN','VAL_DRIVER_MEMORY','32G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_SOLICIT_PORT_IN','VAL_EXECUTOR_MEMORY','32G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_SOLICIT_PORT_IN','VAL_NUM_EXECUTORS','8','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_SOLICIT_PORT_IN','VAL_NUM_EXECUTORS_CORES','4','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_SOLICIT_PORT_IN','QUEUE','reportes','0','1');
SELECT * FROM params WHERE ENTIDAD='OTC_T_SOLICIT_PORT_IN';

