---Realiza un backup de la tabla produccion
CREATE TABLE STAGING.cliente360_bkup20240130 AS
SELECT * FROM STAGING.STG_CLIENTE_360;

--Descompresion de la tabla en produccion
ALTER TABLE STAGING.STG_CLIENTE_360 MOVE NOCOMPRESS;

--Agrega nuevos campos a tabla_destino STG_CLIENTE_360
ALTER TABLE STAGING.STG_CLIENTE_360 
ADD (
listas_negras_contactabilidad	VARCHAR2(2) DEFAULT NULL,
canal_compra_predilecto	VARCHAR2(50) DEFAULT NULL,
monto_factura	DOUBLE PRECISION,
cuotas_terminal	NUMBER(2, 0) DEFAULT NULL,
descripcion_terminal	VARCHAR2(80) DEFAULT NULL,
clasificacion_terminal	VARCHAR2(15) DEFAULT NULL,
televentas	VARCHAR2(2) DEFAULT NULL,
counted_days	NUMBER(5, 0) DEFAULT NULL,
canal_venta	VARCHAR2(50) DEFAULT NULL,
fecha_renovacion_equipo	VARCHAR2(10) DEFAULT NULL,
nse	NUMBER(2, 0) DEFAULT NULL,
estado_abonado	VARCHAR2(3) DEFAULT NULL,
tecnologia	VARCHAR2(10) DEFAULT NULL,
nombre_cliente	VARCHAR2(100) DEFAULT NULL,
fecha_nacimiento	VARCHAR2(10) DEFAULT NULL,
fecha_cambio_plan	VARCHAR2(10) DEFAULT NULL,
fecha_transfer	VARCHAR2(10) DEFAULT NULL,
fecha_baja	VARCHAR2(10) DEFAULT NULL,
usa_app	VARCHAR2(2) DEFAULT NULL,
usuario_app	VARCHAR2(2) DEFAULT NULL,
portabilidad	VARCHAR2(10) DEFAULT NULL,
cod_plan	VARCHAR2(10) DEFAULT NULL,
nombre_plan	VARCHAR2(80) DEFAULT NULL,
ciclo_facturacion	NUMBER(2, 0) DEFAULT NULL,
saldo_cartera	DOUBLE PRECISION,
susp_cobranza	VARCHAR2(40) DEFAULT NULL,
susp_911	VARCHAR2(10) DEFAULT NULL,
susp_cobranza_puntual	VARCHAR2(20) DEFAULT NULL,
susp_fraude	VARCHAR2(10) DEFAULT NULL,
susp_robo	VARCHAR2(10) DEFAULT NULL,
susp_voluntaria	VARCHAR2(10) DEFAULT NULL,
vencimiento_cartera	VARCHAR2(10) DEFAULT NULL,
tipo_movimiento_mes	VARCHAR2(20) DEFAULT NULL,
fecha_movimiento_mes	VARCHAR2(10) DEFAULT NULL,
marca_telefonia	VARCHAR2(15) DEFAULT NULL,
modelo_terminal	VARCHAR2(50) DEFAULT NULL,
os	VARCHAR2(30) DEFAULT NULL,
gama VARCHAR2(7) DEFAULT NULL,
marca_terminal	VARCHAR2(50) DEFAULT NULL,
ubicacion_canton	VARCHAR2(50) DEFAULT NULL,
provincia	VARCHAR2(50) DEFAULT NULL,
ingresos_m1	DOUBLE PRECISION,
ingresos_m2	DOUBLE PRECISION,
ingresos_m3	DOUBLE PRECISION,
cliente_tentado	VARCHAR2(10) DEFAULT NULL,
recargador_m1	VARCHAR2(1) DEFAULT NULL,
recargador_m2	VARCHAR2(1) DEFAULT NULL,
recargador_m3	VARCHAR2(1) DEFAULT NULL,
minutos_prom_3m	DOUBLE PRECISION,
mb_prom_3m	DOUBLE PRECISION,
rango_antiguedad	VARCHAR2(15) DEFAULT NULL,
antiguedad	NUMBER(4, 0) DEFAULT NULL,
edad	NUMBER(3, 0) DEFAULT NULL,
genero	VARCHAR2(10) DEFAULT NULL,
mes_m_m1	VARCHAR2(15) DEFAULT NULL,
recurrencia	VARCHAR2(3) DEFAULT NULL,
ingresos_prom_3m	DOUBLE PRECISION,
moda_combo	VARCHAR2(50) DEFAULT NULL,
valor_moda_combo	VARCHAR2(50) DEFAULT NULL,
valor_max_combo_m1	VARCHAR2(50) DEFAULT NULL,
valor_max_combo_m2	VARCHAR2(50) DEFAULT NULL,
valor_max_combo_m3	VARCHAR2(50) DEFAULT NULL,
estado_vigencia	VARCHAR2(20) DEFAULT NULL,
valor_ultima_recarga	NUMBER(3, 2) DEFAULT NULL,
total_eventos	VARCHAR2(50) DEFAULT NULL,
frecuencia	VARCHAR2(50) DEFAULT NULL,
resencia	NUMBER(5, 0) DEFAULT NULL,
valor_cliente	VARCHAR2(20) DEFAULT NULL,
trafico_saliente_onnet	NUMBER(19,2) DEFAULT NULL,
trafico_saliente_offnet	NUMBER(19,2) DEFAULT NULL,
trafico_entrante_onnet	NUMBER(19,2) DEFAULT NULL,
trafico_entrante_offnet	NUMBER(19,2) DEFAULT NULL,
trafico_saliente	NUMBER(19,2) DEFAULT NULL,
trafico_entrante	NUMBER(19,2) DEFAULT NULL,
ratio	NUMBER(5,3) DEFAULT NULL,
"cluster"	NUMBER(1, 0) DEFAULT NULL,
"rank"	VARCHAR2(1) DEFAULT NULL,
listas_negras_fraude_credito	VARCHAR2(2) DEFAULT NULL,
bonos_m1	VARCHAR2(2) DEFAULT NULL,
bonos_m2	VARCHAR2(2) DEFAULT NULL,
bonos_m3	VARCHAR2(2) DEFAULT NULL,
fecha_activacion_bono	VARCHAR2(10) DEFAULT NULL,
codigo_bono_ondemand    VARCHAR2(5) DEFAULT NULL,
mplay VARCHAR2(2) DEFAULT NULL,
adulto_mayor VARCHAR2(2) DEFAULT NULL,
sub_canal_alta VARCHAR2(50) DEFAULT NULL,
origen_alta_segmento VARCHAR2(20) DEFAULT NULL,
cod_da VARCHAR2(50) DEFAULT NULL,
parque_recargador VARCHAR2(2) DEFAULT NULL,
banco VARCHAR2(50) DEFAULT NULL,
linea_negocio_homologado VARCHAR2(7) DEFAULT NULL
);

--Compresion de la tabla en produccion
ALTER TABLE STAGING.STG_CLIENTE_360 MOVE COMPRESS;
