--                                          PARAMS PARA CATALOGO_CONSOLIDADO
--CAMBIAR LA ENTIDAD
DELETE FROM params_des WHERE entidad='OTC_T_CTL_PRE_USR_NC';
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_CTL_PRE_USR_NC','ETAPA','1',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_CTL_PRE_USR_NC','VAL_USER','nae108834',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_CTL_PRE_USR_NC','VAL_RUTA','/home/nae108834/Catalogo_usuarios_prepago',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_CTL_PRE_USR_NC','VAL_FTP_RUTA','"/Business Intelligence/3_Operaciones/Procesos/EMERGENTE/NC/PARQUE/CATALOGO"',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_CTL_PRE_USR_NC','VAL_FTP_PUERTO','9664',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_CTL_PRE_USR_NC','VAL_FTP_HOSTNAME','fileuio03',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_CTL_PRE_USR_NC','VAL_FTP_PASS','bii2022-NA10',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_CTL_PRE_USR_NC','VAL_FTP_NOM_ARCHIVO','CTL_PRE_USR_NC.xls',0,0);
insert into params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE)VALUES('OTC_T_CTL_PRE_USR_NC','VAL_DIR_HDFS_CAT','db_desarrollo2021.OTC_T_CTL_PRE_USR_NC',1,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_CTL_PRE_USR_NC','VAL_FTP_USER','NABIFI01',0,0);
SELECT * FROM params_des WHERE ENTIDAD='OTC_T_CTL_PRE_USR_NC';


