--                                          PARAMS PARA BASE_CARGA_DESCUENTO_NO_PYMES
--CAMBIAR LA ENTIDAD
DELETE FROM params_des WHERE entidad='OTC_T_DESC_NO_PYMES';
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_DESC_NO_PYMES','ETAPA','1',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_DESC_NO_PYMES','VAL_USER','nae108834',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_DESC_NO_PYMES','VAL_RUTA','/home/nae108834/Base_no_pymes',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_DESC_NO_PYMES','VAL_FTP_RUTA','"/MOVIMIENTOS"',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_DESC_NO_PYMES','VAL_FTP_PUERTO','9694',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_DESC_NO_PYMES','VAL_FTP_HOSTNAME','fileuio03',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_DESC_NO_PYMES','VAL_FTP_PASS','bii2022-NA10',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_DESC_NO_PYMES','VAL_FTP_NOM_ARCHIVO','BASE_CARGA_DESCUENTO_NO_PYMES.xlsx',0,0);
insert into params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_DESC_NO_PYMES','VAL_DIR_HDFS_CAT','db_desarrollo2021.OTC_T_DESC_NO_PYMES',1,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_DESC_NO_PYMES','VAL_FTP_USER','NABIFI01',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_DESC_NO_PYMES','vMASTER','yarn','0','1');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_DESC_NO_PYMES','vDRIVER_MEMORY','16G','0','1');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_DESC_NO_PYMES','vEXECUTOR_MEMORY','16G','0','1');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_DESC_NO_PYMES','vNUM_EXECUTORS','4','0','1');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_DESC_NO_PYMES','vNUM_EXECUTORS_CORES','4','0','1');
SELECT * FROM params_des WHERE ENTIDAD='OTC_T_DESC_NO_PYMES';

