
-------PARAMS PARA EXTRACTOR DE MOVIMIENTOS
DELETE FROM params_des WHERE entidad='EXT_MVMNTS0010';
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0010','ETAPA','1',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0010','vRUTA','/home/nae108834/Movimientos',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0010','vFTP_RUTA_OUT','/PROYECTO_COMISIONES_PRODUCCION/EXT_MOVIMIENTOS',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0010','vFTP_USER_OUT','NABIFI01',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0010','vFTP_PUERTO_OUT','9694',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0010','vFTP_HOSTNAME_OUT','fileuio03',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0010','vFTP_PASS_OUT','bii2022-NA10',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0010','vFTP_NOM_ARCHIVO','Extractor_Movimientos_',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0010','vRUTA_IN','/home/nae108834/Movimientos/Input',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0010','vARCH_XTRCTR','/home/nae108834/Movimientos/Input/Extractor_Movimientos.txt',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0010','vTMain','db_desarrollo2021.otc_t_ext_movimientos',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0010','vTAjust','db_desarrollo2021.otc_t_ajustes_movimientos',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0010','vNOM_PROCESO','EXTRACTOR_DE_MOVIMIENTOS',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0010','vSFTP_PUERTO_OUT','22','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0010','vSFTP_USER_OUT','telefonicaecuadorprod','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0010','vSFTP_HOSTNAME_OUT','ftp.cloud.varicent.com','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0010','vSFTP_PASS_OUT','RqiZ2lkJmeiQTi2hvRwd','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0010','vSFTP_RUTA_OUT','/Data','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0010','vNOM_ARCHIVO_OUT','Extractor_Movimientos','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0010','vMASTER','yarn','0','1');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0010','vDRIVER_MEMORY','16G','0','1');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0010','vEXECUTOR_MEMORY','16G','0','1');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0010','vNUM_EXECUTORS','4','0','1');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXT_MVMNTS0010','vNUM_EXECUTORS_CORES','4','0','1');
SELECT * FROM params_des WHERE ENTIDAD='EXT_MVMNTS0010';


