--                                          PARAMS PARA perimetros transfer in y altas
--CAMBIAR LA ENTIDAD
DELETE FROM params_des WHERE entidad='OTC_T_PRMTR_ALTAS_TI';
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_PRMTR_ALTAS_TI','ETAPA','1',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_PRMTR_ALTAS_TI','VAL_USER','nae108834',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_PRMTR_ALTAS_TI','VAL_RUTA','/home/nae108834/Perimetro_movimientos',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_PRMTR_ALTAS_TI','VAL_FTP_RUTA','"/MOVIMIENTOS"',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_PRMTR_ALTAS_TI','VAL_FTP_PUERTO','9694',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_PRMTR_ALTAS_TI','VAL_FTP_HOSTNAME','fileuio03',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_PRMTR_ALTAS_TI','VAL_FTP_PASS','bii2022-NA10',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_PRMTR_ALTAS_TI','VAL_FTP_NOM_ARCHIVO','Perimetro Septiembre22_EN Altas.xlsx',0,0);
--INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_PRMTR_ALTAS_TI','VAL_FTP_NOM_ARCHIVO','Perimetro Octubre22_EN Altas.xlsx',0,0);
--INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_PRMTR_ALTAS_TI','VAL_FTP_NOM_ARCHIVO','Perimetro Noviembre22_EN Altas.xlsx',0,0);
insert into params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE)VALUES('OTC_T_PRMTR_ALTAS_TI','VAL_DIR_HDFS_CAT','db_desarrollo2021.OTC_T_PRMTR_ALTAS_TI',1,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_PRMTR_ALTAS_TI','VAL_FTP_USER','NABIFI01',0,0);
SELECT * FROM params_des WHERE ENTIDAD='OTC_T_PRMTR_ALTAS_TI';

--                                          PARAMS PARA perimetros transfer out y bajas
--CAMBIAR LA ENTIDAD
DELETE FROM params_des WHERE entidad='OTC_T_PRMTR_BAJAS_TO';
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_PRMTR_BAJAS_TO','ETAPA','1',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_PRMTR_BAJAS_TO','VAL_USER','nae108834',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_PRMTR_BAJAS_TO','VAL_RUTA','/home/nae108834/Perimetro_movimientos',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_PRMTR_BAJAS_TO','VAL_FTP_RUTA','"/MOVIMIENTOS"',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_PRMTR_BAJAS_TO','VAL_FTP_PUERTO','9694',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_PRMTR_BAJAS_TO','VAL_FTP_HOSTNAME','fileuio03',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_PRMTR_BAJAS_TO','VAL_FTP_PASS','bii2022-NA10',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_PRMTR_BAJAS_TO','VAL_FTP_NOM_ARCHIVO','Perimetro Septiembre22_EN Bajas.xlsx',0,0);
--INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_PRMTR_BAJAS_TO','VAL_FTP_NOM_ARCHIVO','Perimetro Octubre22_EN Bajas.xlsx',0,0);
--INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_PRMTR_BAJAS_TO','VAL_FTP_NOM_ARCHIVO','Perimetro Noviembre22_EN Bajas.xlsx',0,0);
insert into params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE)VALUES('OTC_T_PRMTR_BAJAS_TO','VAL_DIR_HDFS_CAT','db_desarrollo2021.OTC_T_PRMTR_BAJAS_TO',1,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('OTC_T_PRMTR_BAJAS_TO','VAL_FTP_USER','NABIFI01',0,0);
SELECT * FROM params_des WHERE ENTIDAD='OTC_T_PRMTR_BAJAS_TO';
